/* Autogenerated by png2wx.pl on Mon Oct 11 11:04:01 2021 */
#ifndef MEDIAPLAYER_ICON_H
#define MEDIAPLAYER_ICON_H 1

#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#	include <wx/wx.h>
#endif

extern void initialize_images(void);

extern wxBitmap *mediaPlayerControlImage;

#endif /* MEDIAPLAYER_ICON_H */
